// World pre-seeding for the multi-agent demo.
//
// The underlying world is generated by flying-squid's diamond_square
// generator — natural hills, forests, stone layers. We just drop a few
// landmarks so the demo has a reliable "base" (chest + crafting_table)
// and a handful of exposed diamond veins within reach.

const { Vec3 } = require("vec3");

/** Scan down from sky level and return the y of the first solid block. */
async function findSurfaceY(overworld, x, z, maxY = 80) {
  for (let y = maxY; y >= 0; y--) {
    const b = await overworld.getBlock(new Vec3(x, y, z));
    if (!b) continue;
    if (b.name === "air" || b.name === "cave_air" || b.name === "void_air") continue;
    if (b.name === "water" || b.name === "lava") continue;
    // oak_leaves count as "canopy" — keep descending to find ground
    if (b.name === "oak_leaves" || b.name === "grass" || b.name === "tall_grass") continue;
    return y;
  }
  return 4; // fallback
}

async function seedWorld(server, mcVersion, center) {
  const mcData = require("minecraft-data")(mcVersion);
  const overworld = server.overworld;

  const cx = Math.floor(center.x);
  const cz = Math.floor(center.z);

  const blockByName = (name) => {
    const b = mcData.blocksByName[name];
    if (!b) throw new Error(`unknown block: ${name}`);
    return b;
  };

  async function set(pos, name) {
    const b = blockByName(name);
    const stateId = b.defaultState ?? b.minStateId ?? b.id;
    await server.setBlock(overworld, pos, stateId);
  }

  // ── 1. Base plaza: find flat-ish ground, clear a 3x3 pad, place crafting + chest ──
  // Search a ring of candidate spots near spawn for a place where the surface
  // is relatively flat (adjacent surface heights within 1 block).
  const candidates = [];
  for (let r = 3; r <= 6; r++) {
    for (let dx = -r; dx <= r; dx++) {
      for (let dz = -r; dz <= r; dz++) {
        if (Math.abs(dx) !== r && Math.abs(dz) !== r) continue; // ring only
        candidates.push({ x: cx + dx, z: cz + dz });
      }
    }
  }
  let best = null;
  for (const c of candidates) {
    const ys = await Promise.all(
      [[0,0],[1,0],[0,1],[-1,0],[0,-1]].map(([dx,dz]) =>
        findSurfaceY(overworld, c.x + dx, c.z + dz)
      )
    );
    const range = Math.max(...ys) - Math.min(...ys);
    if (range <= 1) { best = { ...c, y: ys[0] }; break; }
    if (!best || range < best.range) best = { ...c, y: ys[0], range };
  }
  if (!best) best = { x: cx + 3, z: cz, y: await findSurfaceY(overworld, cx + 3, cz) };
  const baseY = best.y;

  // Clear canopy above base (in case a tree is in the way)
  for (let dx = -1; dx <= 2; dx++) {
    for (let dz = -1; dz <= 1; dz++) {
      for (let dy = 1; dy <= 6; dy++) {
        await set(new Vec3(best.x + dx, baseY + dy, best.z + dz), "air");
      }
    }
  }
  // Flatten pad to grass/dirt
  for (let dx = -1; dx <= 2; dx++) {
    for (let dz = -1; dz <= 1; dz++) {
      await set(new Vec3(best.x + dx, baseY, best.z + dz), "grass_block");
    }
  }

  const craftPos = new Vec3(best.x, baseY + 1, best.z);
  await set(craftPos, "crafting_table");
  const chestPos = new Vec3(best.x + 2, baseY + 1, best.z);
  await set(chestPos, "chest");

  // ── 2. Exposed diamond veins: pick spots ~15-25 blocks in 4 directions ──
  // Drop them ON the surface so findBlock finds them. In real minecraft
  // diamonds are buried, but for the demo we want visible "go-get-that" spots.
  const veinOffsets = [
    { dx:  18, dz:   5 }, // east
    { dx: -15, dz:  12 }, // west
    { dx:   8, dz: -18 }, // south
    { dx: -12, dz: -14 }, // south-west
    { dx:  22, dz: -10 }, // east-south
  ];
  const diamondSpots = [];
  for (const off of veinOffsets) {
    const x = cx + off.dx;
    const z = cz + off.dz;
    const y = await findSurfaceY(overworld, x, z);
    // Clear one block above (in case leaves/grass), place a 2x1x2 vein on the surface
    for (let ddx = 0; ddx < 2; ddx++) {
      for (let ddz = 0; ddz < 2; ddz++) {
        await set(new Vec3(x + ddx, y + 1, z + ddz), "air");
        await set(new Vec3(x + ddx, y,     z + ddz), "diamond_ore");
      }
    }
    diamondSpots.push(new Vec3(x, y, z));
  }

  return {
    spawn: new Vec3(cx, baseY, cz),
    basePlaza: new Vec3(best.x, baseY, best.z),
    craftingTable: craftPos,
    sharedChest: chestPos,
    diamondSpots,
  };
}

/**
 * Force the bot inventory empty at spawn. flying-squid sometimes hands out
 * a stray iron_pickaxe. LOCAL ONLY — server-side tracking over the duplex
 * pair is unreliable.
 */
async function seedBotInventory(bot, mcVersion) {
  for (let slot = 9; slot <= 45; slot++) {
    if (bot.inventory.updateSlot) bot.inventory.updateSlot(slot, null);
    else bot.inventory.slots[slot] = null;
  }
}

module.exports = { seedWorld, seedBotInventory };
