// World pre-seeding for the multi-agent demo.
//
// The underlying world is generated by flying-squid's diamond_square
// generator — natural hills, forests, stone layers. We just drop a few
// landmarks so the demo has a reliable "base" (chest + crafting_table)
// and a handful of exposed diamond veins within reach.

const { Vec3 } = require("vec3");

/** Scan down from sky level and return the y of the first solid block. */
async function findSurfaceY(overworld, x, z, maxY = 80) {
  for (let y = maxY; y >= 0; y--) {
    const b = await overworld.getBlock(new Vec3(x, y, z));
    if (!b) continue;
    if (b.name === "air" || b.name === "cave_air" || b.name === "void_air") continue;
    if (b.name === "water" || b.name === "lava") continue;
    // oak_leaves count as "canopy" — keep descending to find ground
    if (b.name === "oak_leaves" || b.name === "grass" || b.name === "tall_grass") continue;
    return y;
  }
  return 4; // fallback
}

async function seedWorld(server, mcVersion, center) {
  const mcData = require("minecraft-data")(mcVersion);
  const overworld = server.overworld;

  const cx = Math.floor(center.x);
  const cz = Math.floor(center.z);

  const blockByName = (name) => {
    const b = mcData.blocksByName[name];
    if (!b) throw new Error(`unknown block: ${name}`);
    return b;
  };

  async function set(pos, name) {
    const b = blockByName(name);
    const stateId = b.defaultState ?? b.minStateId ?? b.id;
    await server.setBlock(overworld, pos, stateId);
  }

  // ── 1. Base plaza: pick a spot in the natural terrain that's both HIGH
  // (above surrounding terrain so bots aren't visually buried) AND FLAT
  // (so they can stand cleanly). Then clear sky above + level a small pad.
  //
  // Scan a wide area for the candidate that maximises (heightAboveAvg - localVariance).
  const SEARCH_R = 14;
  const scan = [];
  for (let dx = -SEARCH_R; dx <= SEARCH_R; dx += 2) {
    for (let dz = -SEARCH_R; dz <= SEARCH_R; dz += 2) {
      scan.push({ x: cx + dx, z: cz + dz });
    }
  }
  // Get surface ys for all scan points + a few neighbors per candidate
  const surfaceCache = new Map();
  const surfAt = async (x, z) => {
    const k = `${x},${z}`;
    if (surfaceCache.has(k)) return surfaceCache.get(k);
    const y = await findSurfaceY(overworld, x, z);
    surfaceCache.set(k, y);
    return y;
  };
  // Average surface across the whole scan
  const allYs = await Promise.all(scan.map((p) => surfAt(p.x, p.z)));
  const avgY = allYs.reduce((a, b) => a + b, 0) / allYs.length;

  let bestPick = null;
  let bestScore = -Infinity;
  for (let i = 0; i < scan.length; i++) {
    const p = scan[i];
    const center = allYs[i];
    // Sample a 5x5 neighborhood for local variance + average
    const neigh = [];
    for (let nx = -2; nx <= 2; nx++) {
      for (let nz = -2; nz <= 2; nz++) {
        neigh.push(await surfAt(p.x + nx, p.z + nz));
      }
    }
    const lo = Math.min(...neigh);
    const hi = Math.max(...neigh);
    const variance = hi - lo;
    if (variance > 2) continue; // require a 5x5 area within 2 blocks vertically
    const heightAboveAvg = center - avgY;
    const score = heightAboveAvg * 3 - variance; // bias strongly toward high+flat
    if (score > bestScore) {
      bestScore = score;
      bestPick = { x: p.x, z: p.z, y: center };
    }
  }
  // Fallback if nothing flat enough — just use highest sample
  if (!bestPick) {
    let h = -Infinity, hi = 0;
    for (let i = 0; i < scan.length; i++) if (allYs[i] > h) { h = allYs[i]; hi = i; }
    bestPick = { x: scan[hi].x, z: scan[hi].z, y: allYs[hi] };
  }

  const baseX = bestPick.x;
  const baseZ = bestPick.z;
  const baseY = bestPick.y;

  // Clear sky above the pad (any overhanging leaves/dirt)
  for (let dx = -2; dx <= 3; dx++) {
    for (let dz = -2; dz <= 2; dz++) {
      for (let dy = 1; dy <= 8; dy++) {
        await set(new Vec3(baseX + dx, baseY + dy, baseZ + dz), "air");
      }
    }
  }
  // Level the pad to the chosen y, grass cap on top
  for (let dx = -2; dx <= 3; dx++) {
    for (let dz = -2; dz <= 2; dz++) {
      await set(new Vec3(baseX + dx, baseY, baseZ + dz), "grass_block");
    }
  }

  const craftPos = new Vec3(baseX + 2, baseY + 1, baseZ);
  await set(craftPos, "crafting_table");

  // Shared "chest" — flying-squid's setBlock doesn't initialize the chest's
  // tile-entity NBT, so prismarine-viewer renders an actual `chest` as
  // invisible. Use a 1×2 stack of solid blocks instead: glowstone base +
  // diamond_block top. Glows bright, sparkles, impossible to miss.
  const chestPos = new Vec3(baseX + 3, baseY + 1, baseZ);
  await set(chestPos, "glowstone");
  await set(chestPos.offset(0, 1, 0), "diamond_block");
  // Four torches around it for extra visibility (and pretty light)
  for (const off of [
    [-1, 0, 0],
    [1, 0, 0],
    [0, 0, -1],
    [0, 0, 1],
  ]) {
    const tp = chestPos.offset(...off);
    await set(tp, "torch");
  }
  const best = { x: baseX, z: baseZ, y: baseY };

  // ── 2. Exposed diamond veins: ONE per compass direction so the team
  // demo's directional role-assignment has unambiguous targets. Each is
  // ~22 blocks from world center; placement matches TEAM_ROLE in
  // teamOrchestrator.js (Alice=East, Bob=West, Carl=South, Dana=North).
  const veinOffsets = [
    { dx:  22, dz:   2 }, // EAST   → Alice
    { dx: -22, dz:  -2 }, // WEST   → Bob
    { dx:   2, dz: -22 }, // SOUTH  → Carl
    { dx:  -2, dz:  22 }, // NORTH  → Dana
    { dx:  16, dz:  16 }, // NE bonus (in case anyone needs a second vein)
  ];
  const diamondSpots = [];
  for (const off of veinOffsets) {
    const x = cx + off.dx;
    const z = cz + off.dz;
    const y = await findSurfaceY(overworld, x, z);
    // Clear one block above (in case leaves/grass), place a 2x1x2 vein on the surface
    for (let ddx = 0; ddx < 2; ddx++) {
      for (let ddz = 0; ddz < 2; ddz++) {
        await set(new Vec3(x + ddx, y + 1, z + ddz), "air");
        await set(new Vec3(x + ddx, y,     z + ddz), "diamond_ore");
      }
    }
    diamondSpots.push(new Vec3(x, y, z));
  }

  return {
    spawn: new Vec3(cx, baseY, cz),
    basePlaza: new Vec3(best.x, baseY, best.z),
    craftingTable: craftPos,
    sharedChest: chestPos,
    diamondSpots,
  };
}

/**
 * Force the bot inventory empty at spawn. flying-squid sometimes hands out
 * a stray iron_pickaxe. LOCAL ONLY — server-side tracking over the duplex
 * pair is unreliable.
 */
async function seedBotInventory(bot, mcVersion) {
  for (let slot = 9; slot <= 45; slot++) {
    if (bot.inventory.updateSlot) bot.inventory.updateSlot(slot, null);
    else bot.inventory.slots[slot] = null;
  }
}

module.exports = { seedWorld, seedBotInventory };
